### ISSUE TITLE
Add support for Spark 3

### ISSUE THREAD

**Issue by z4f1r0v** [leobenkel/ZparkIO#94]
The latest Databricks [runtime](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/7.5) supports Spark 3.0.1. To enable adoption across the growing Spark community on Azure, Zparkio should support the third major release of Spark.

**Comment by leobenkel** [comment]
The step would be to add it to this file: https://github.com/leobenkel/ZparkIO/blob/main/sparkVersions 

And see what breaks. Hopefully nothing ? 

But all deployment are blocked right now because of TravisCI turning off support for open source project: https://github.com/leobenkel/ZparkIO/issues/88 :(

**Comment by z4f1r0v** [comment]
I'm on it :)

**Comment by z4f1r0v** [comment]
https://github.com/leobenkel/ZparkIO/pull/95

**Comment by leobenkel** [comment]
Thank you @z4f1r0v !
